VideoProject/Controllers/ButtonSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoProject.Core;
using VideoProject.Model;

namespace VideoProject.Controllers
{
    public class ButtonSetController : BaseController
    {
        #region Button Set
        public ActionResult ButtonSetList()
        {
            return View();
        }
        public PartialViewResult AddButtonSetPartialView()
        {
            return PartialView("~/Views/ButtonSet/_AddButtonSetPartial.cshtml");
        }

        [HttpGet]
        public JsonResult GetButtonSetList()
        {
            int UserID = Convert.ToInt32(HttpContext.Session.Contents["UserId"]);

            ButtonSetRepository bsr = new ButtonSetRepository();
            List<ButtonSetModel> lstButtonSet = bsr.GetButtonSetList(UserID);
            return Json(new { data = lstButtonSet }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveButtonSet(ButtonSetModel bsm)
        {
            bsm.UserID = Convert.ToInt32(HttpContext.Session.Contents["UserId"]);

            ButtonSetRepository bsr = new ButtonSetRepository();
            return Json(bsr.SaveButtonSetDetail(bsm));
        }
        #endregion
    }
}

VideoProject/Controllers/VideoController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoProject.Core;
using VideoProject.Model;
using System.IO;

namespace VideoProject.Controllers
{
    public class VideoController : BaseController
    {
        //
        // GET: /Video/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateCampaign()
        {
            return View();
        }

        public ActionResult CreateNewCampaign(int? id)
        {
            int VideoCampaignID = id ?? 0;
            if (VideoCampaignID > 0)
            {
                VideoDetailRepository vdr = new VideoDetailRepository();
                ViewBag.VideoCampaignModel = vdr.GetVideoCampaignModelByID(VideoCampaignID);
            }

            return View();
        }

        [HttpPost]
        public JsonResult SaveNewCampaign(VideoCampaignModel vcm)
        {
            vcm.UserId = Convert.ToInt32(HttpContext.Session.Contents["UserId"]);
            VideoDetailRepository vdr = new VideoDetailRepository();
            vcm.VideoCampaignID = vcm.NewVideoCampaignID == 0 ? vcm.VideoCampaignID : vcm.NewVideoCampaignID;
            int VideoCampaignID = vdr.SaveCampaignDetail(vcm);
            return Json(VideoCampaignID);
        }

        public ActionResult VideoCampaignList()
        {
            int UserId = Convert.ToInt32(HttpContext.Session.Contents["UserId"]);
            VideoDetailRepository vdr = new VideoDetailRepository();
            List<VideoCampaignModel> lstVideoCampaign = vdr.GetVideoCampaignList(UserId);
            return View("VideoCampaignList", lstVideoCampaign);
        }

        public PartialViewResult ChangeColorPartialView()
        {
            return PartialView("~/Views/Video/_ChangeColorPartial.cshtml");
        }

        public JsonResult SubscribeSave(string EmailId)
        {
            try
            {
                var apiKey = "5246da6b0cde2b3335025f0f335dce47-us7"; // your API key here (no, this is not a real one!)
                var listId = "792b360360"; // your list ID here
                var subscribeRequest = new
                {
                    apikey = apiKey,
                    id = listId,
                    email = new
                    {
                        email = EmailId
                    },
                    double_optin = true,
                };
                var requestJson = JsonConvert.SerializeObject(subscribeRequest);

                var responseString = CallMailChimpApi("lists/subscribe.json", requestJson);
                dynamic responseObject = JsonConvert.DeserializeObject(responseString);
                if ((responseObject.email != null) && (responseObject.euid != null))
                {
                    // successful!
                    return Json(new object[] { true, "Success" });
                }
                else
                {
                    string name = responseObject.name;
                    if (name == "List_AlreadySubscribed")
                    {
                        return Json(new object[] { false, "Email already subscribed" });
                    }
                    else
                    {
                        string error = responseObject.error;
                        return Json(new object[] { false, error });
                    }
                }
            }
            catch (Exception ex)
            {
                return Json(new object[] { false, "Error" });
            }
        }

        private static string CallMailChimpApi(string method, string requestJson)
        {
            var endpoint = String.Format("https://{0}.api.mailchimp.com/2.0/{1}", "us7", method);
            var wc = new System.Net.WebClient();
            try
            {
                return wc.UploadString(endpoint, requestJson);
            }
            catch (System.Net.WebException we)
            {
                using (var sr = new System.IO.StreamReader(we.Response.GetResponseStream()))
                {
                    return sr.ReadToEnd();
                }
            }
        }

        [HttpPost]
        public ActionResult UploadFBShareImages()
        {
            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    string upload_url = string.Empty;

                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[i];
                        string fname;

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = Session.SessionID + "_" + DateTime.Now.ToString("MM-dd-yyyy_hhsstt") + "_" + file.FileName;
                        }

                        string FBShareImages = Server.MapPath("~/FBShareImages/User/" + Session["UserId"] + "/");

                        if (!Directory.Exists(FBShareImages))
                        {
                            Directory.CreateDirectory(FBShareImages);
                        }

                        upload_url = ResolveServerUrl(VirtualPathUtility.ToAbsolute("~/FBShareImages/User/" + Session["UserId"] + "/" + fname), false);

                        // Get the complete folder path and store the file inside it.  
                        fname = Path.Combine(FBShareImages, fname);

                        file.SaveAs(fname);
                    }
                    // Returns message that successfully uploaded  
                    return Json(upload_url);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }

        public static string ResolveServerUrl(string serverUrl, bool forceHttps)
        {
            if (serverUrl.IndexOf("://") > -1)
                return serverUrl;

            string newUrl = serverUrl;
            Uri originalUri = System.Web.HttpContext.Current.Request.Url;
            newUrl = (forceHttps ? "https" : originalUri.Scheme) +
                "://" + originalUri.Authority + newUrl;
            return newUrl;
        }
        public ActionResult VideoEdit(string id, int campaginID)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoModel vm = new VideoModel();
            if (!string.IsNullOrEmpty(id))
            {
                vm = vdr.GetVideoModelByID(id, campaginID);
            }
            string[] spliturl = vm.URL.Split('/');
            vm.VideoCampaignID = campaginID;

            if (spliturl[2].Contains("youtube"))
            {
                vm.VideoURLID = spliturl[spliturl.Length - 1].Substring(8, spliturl[spliturl.Length - 1].Length - 8);
                vm.VideoType = spliturl[2].Split('.')[1];

            }
            else
            {
                vm.VideoURLID = spliturl[spliturl.Length - 1];
                vm.VideoType = spliturl[2].Split('.')[0];

            }
            //vm.VideoElements.Add(new VideoElement { ElementName = "" });
            return View(vm);
        }
        [HttpPost]
        public int VideoEdit(List<VideoElement> model)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoModel vm = new VideoModel();
            vm.UniqueID = model.ElementAt(0).UniqueID;
            vm.VideoElements = model;
            return vdr.SaveVideoElement(vm);
        }
        public ActionResult VideoPreview(string id, int campaginID)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoModel vm = new VideoModel();
            if (!string.IsNullOrEmpty(id))
            {
                vm = vdr.GetVideoModelByID(id, campaginID);
            }
            string[] spliturl = vm.URL.Split('/');
            vm.VideoCampaignID = campaginID;
            if (spliturl[2].Contains("youtube"))
            {
                vm.VideoURLID = spliturl[spliturl.Length - 1].Substring(8, spliturl[spliturl.Length - 1].Length - 8);
                vm.VideoType = spliturl[2].Split('.')[1];

            }
            else
            {
                vm.VideoURLID = spliturl[spliturl.Length - 1];
                vm.VideoType = spliturl[2].Split('.')[0];

            }
            //  vm.VideoURLID = spliturl[spliturl.Length - 1];
            //  vm.VideoType = spliturl[2].Split('.')[0];
            //vm.VideoElements.Add(new VideoElement { ElementName = "" });
            return View("VideoPreview", vm);
        }
        public ActionResult CampaignVideoPreview(int campaginID)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoModel vm = new VideoModel();
            string id = "";
            id = vdr.GetStartVideoID(campaginID);
            if (!string.IsNullOrEmpty(id))
            {
                vm = vdr.GetVideoModelByID(id, campaginID);
            }
            string[] spliturl = vm.URL.Split('/');

VideoProject/Controllers/VideoPlayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoProject.Core;
using VideoProject.Model;

namespace VideoProject.Controllers
{
    public class VideoPlayController : Controller
    {
        //
        // GET: /VideoPlay/

        public ActionResult Index()
        {
            List<VideoHierarchyModel> objVideoDetailModel = new List<VideoHierarchyModel>();
            VideoHierarchyModel objVideoModel = new VideoHierarchyModel();
            objVideoModel.VideoID = 1;
            objVideoModel.IsStart = true;
            //objVideoModel.VideoURL = "https://www.youtube.com/watch?v=1Mlhnt0jMlg";
            //objVideoModel.VideoURL = "https://vimeo.com/ondemand/365film/58622266";
            objVideoModel.VideoURL = "https://vimeo.com/27221475";
            objVideoModel.QuestionID = 1;
            objVideoModel.QueDetail = "First Question";
            objVideoModel.AnswerID = 1;
            objVideoModel.AnsDetail = "First 1";
            objVideoModel.NextVideoID = 2;

            objVideoDetailModel.Add(objVideoModel);

            objVideoModel = new VideoHierarchyModel();
            objVideoModel.VideoID = 1;
            objVideoModel.IsStart = true;
            objVideoModel.VideoURL = "https://www.youtube.com/watch?v=uIxnTi4GmCo ";
            objVideoModel.QuestionID = 1;
            objVideoModel.QueDetail = "First Question";
            objVideoModel.AnswerID = 2;
            objVideoModel.AnsDetail = "Second 2";
            objVideoModel.NextVideoID = 3;
            objVideoDetailModel.Add(objVideoModel);

            objVideoModel = new VideoHierarchyModel();
            objVideoModel.VideoID = 2;
            objVideoModel.IsStart = false;
            objVideoModel.VideoURL = "https://www.youtube.com/watch?v=z2z857RSfhk ";
            objVideoModel.QuestionID = 3;
            objVideoModel.QueDetail = "Second Question";
            objVideoModel.AnswerID = 3;
            objVideoModel.AnsDetail = "Answer Second Question";
            objVideoModel.NextVideoID = 5;
            objVideoDetailModel.Add(objVideoModel);

            objVideoModel = new VideoHierarchyModel();
            objVideoModel.VideoID = 3;
            objVideoModel.IsStart = false;
            objVideoModel.VideoURL = "https://www.youtube.com/watch?v=z2z857RSfhk ";
            objVideoModel.QuestionID = -1;
            objVideoModel.QueDetail = "";
            objVideoModel.AnswerID = -1;
            objVideoModel.AnsDetail = "";
            objVideoModel.NextVideoID = -1;
            objVideoDetailModel.Add(objVideoModel);

            objVideoModel = new VideoHierarchyModel();
            objVideoModel.VideoID = 5;
            objVideoModel.IsStart = false;
            objVideoModel.VideoURL = "https://www.youtube.com/watch?v=z2z857RSfhk ";
            objVideoModel.QuestionID = -1;
            objVideoModel.QueDetail = "";
            objVideoModel.AnswerID = -1;
            objVideoModel.AnsDetail = "";
            objVideoModel.NextVideoID = -1;
            objVideoDetailModel.Add(objVideoModel);

            return View(objVideoDetailModel.ToList());
        }


        public ActionResult GetPreviewPartialPage()
        {
            return View();
        }

        public ActionResult PlayVideo(int id = 0)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoDetailModel vcm = vdr.GetUserVideoHierarchy(id);
            ViewBag.VideoDetailModel = vcm;

            return View();
        }

        public PartialViewResult PlayVideoPartialView(int id = 0)
        {
            VideoDetailRepository vdr = new VideoDetailRepository();
            VideoDetailModel vcm = vdr.GetUserVideoHierarchy(id);
            ViewBag.VideoDetailModel = vcm;

            return PartialView("~/Views/VideoPlay/_PlayVideoPartialView.cshtml");

        }

        public ActionResult TestEmbeddedCode()
        {
            return View();
        }

        public ActionResult ButtonSetDisplay(int id = 0)
        {
            ButtonSetRepository bsr = new ButtonSetRepository();
            ButtonSetModel bsm = bsr.GetButtonSetDetail(id);
            return View(bsm);
        }
    }
}

VideoProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>@{ViewBag.Title = "_Layout";}</title>

    @RenderSection("CSS", required: false)

    @*<link href="@Url.Content("~/Content/Css/MainStyle.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/JS/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="@Url.Content("~/Content/JS/jquery3.2.1.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/JS/jquery-ui.min.js")"></script>
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/JS/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/JS/bootbox.min.js")"></script>*@


    <link rel="stylesheet" href="~/Content/Css/campagin/vendor/bootstrap.min.css">


    @RenderSection("JavaScript", required: false)

    <style>
        .loading-image {
            position: absolute;
            top: 50%;
            left: 50%;
            z-index: 10;
        }

        .loader {
            display: none;
            width: 200px;
            height: 200px;
            position: fixed;
            top: 50%;
            left: 50%;
            text-align: center;
            margin-left: -50px;
            margin-top: -100px;
            z-index: 2;
            overflow: hidden;
        }
    </style>

</head>
<body>

    <div class="loader">
        <center>
       <img class="loading-image" src="~/Content/Images/loader.gif" alt="loading..">
   </center>
    </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        @*<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>*@
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand PadTtitle" href="#">VIDEO &nbsp;<span style="color: #228B22">PROJECT</span></a>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CreateNewCampaign", "Video")" target="_blank">New Campaign</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("VideoCampaignList", "Video")" target="_blank">CampaignList</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ButtonSetList", "ButtonSet")" target="_blank">ButtonSetList</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("TestEmbeddedCode", "VideoPlay")" target="_blank">TestEmbedCode</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Clients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">My Account</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Login", "Login")">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div id="dvFadeMessage" class="col-md-12" style="display: none;"></div>
    @RenderBody()

</body>
</html>